
import { LocationOption, LocationType } from "./types";

export const LOCATIONS: LocationOption[] = [
  // Airports
  {
    id: 'IN1T', shortCode: 'IN1T', name: '인천공항 T1', type: LocationType.AIRPORT,
    description: '3층 출국장 A 카운터', address: '인천광역시 중구 공항로 270',
    name_en: 'Incheon Airport T1', description_en: '3F Departure Hall A Counter', address_en: '270, Gonghang-ro, Jung-gu, Incheon',
    name_ja: '仁川空港 T1', description_ja: '3階 出発ロビー Aカウンター', address_ja: '仁川広域市 中区 空港路 270',
    name_zh: '仁川机场 T1', description_zh: '3楼 出境大厅 A 柜台', address_zh: '仁川广域市 中区 机场路 270',
    pickupGuide_en: '3F Departure Hall A counter, look for the yellow Beeliber sign.',
    pickupGuide_ja: '3階 出発ロビー Aカウンター、黄色のBeeliber의看板を探してください。',
    pickupGuide_zh: '请在3楼出境大厅A柜台前寻找黄色的Beeliber标志。',
    businessHours: '07:00 - 22:00',
    businessHours_en: '07:00 - 22:00',
    businessHours_ja: '07:00 - 22:00',
    businessHours_zh: '07:00 - 22:00',
    supportsDelivery: true, supportsStorage: false, lat: 37.4485, lng: 126.4525,
    originSurcharge: 3000, destinationSurcharge: 3000,
    isActive: true
  },
  {
    id: 'IN2T', shortCode: 'IN2T', name: '인천공항 T2', type: LocationType.AIRPORT,
    description: '3층 출국장 H 카운터', address: '인천광역시 중구 제2터미널대로 446',
    name_en: 'Incheon Airport T2', description_en: '3F Departure Hall H Counter', address_en: '446, Je2terminal-daero, Jung-gu, Incheon',
    name_ja: '仁川空港 T2', description_ja: '3階 出発ロビー Hカウンター', address_ja: '仁川広域市 中区 第2터미널大路 446',
    name_zh: '仁川机场 T2', description_zh: '3楼 出境大厅 H 柜台', address_zh: '仁川广域市 中区 第2航站楼大路 446',
    pickupGuide_en: '3F Departure Hall H Counter, meet our staff with the Beeliber vest.',
    pickupGuide_ja: '3階 出発ロビー Hカウンター、Beeliber의ベストを着用したスタッフ과 만나세요.',
    pickupGuide_zh: '请在3楼出境大厅H柜台前与我们的工作人员会面。',
    businessHours: '07:00 - 22:00',
    businessHours_en: '07:00 - 22:00',
    businessHours_ja: '07:00 - 22:00',
    businessHours_zh: '07:00 - 22:00',
    supportsDelivery: true, supportsStorage: false, lat: 37.4687, lng: 126.4344,
    originSurcharge: 3000, destinationSurcharge: 3000,
    isActive: true
  },
  {
    id: 'GMP', shortCode: 'GMP', name: '김포공항', type: LocationType.AIRPORT,
    description: '국제선 1층 입국장 수화물 보관소', address: '서울시 강서구 하늘길 111',
    name_en: 'Gimpo Airport', description_en: 'Intl Terminal 1F Arrival Baggage Storage', address_en: '111, Haneul-gil, Gangseo-gu, Seoul',
    name_ja: '金浦空港', description_ja: '国際線 1階 到着ロビー 手荷물保管所', address_ja: 'ソウル市 江西区 ハヌルギル 111',
    name_zh: '金浦机场', description_zh: '国际线 1楼 入境大厅 行理寄存处', address_zh: '首尔市 江西区 天空路 111',
    pickupGuide_en: 'Intl Terminal 1F Arrival, drop off at "Left Baggage" storage.',
    pickupGuide_ja: '国際線 1階 到着ロビー 手荷物保管所(Left Baggage)にお預けください。',
    pickupGuide_zh: '请寄存在金浦机场国际线1楼入境大厅行李寄存处(Left Baggage)。',
    businessHours: '07:00 - 22:00',
    businessHours_en: '07:00 - 22:00',
    businessHours_ja: '07:00 - 22:00',
    businessHours_zh: '07:00 - 22:00',
    supportsDelivery: true, supportsStorage: false, lat: 37.5596, lng: 126.7940,
    originSurcharge: 2000, destinationSurcharge: 2000,
    isActive: true
  },

  // City Branches (Partners)
  {
    id: 'HBO', shortCode: 'HBO', name: '홍대 바오점', type: LocationType.PARTNER,
    description: '홍대입구역 9번 출구 도보 3분', address: '홍익로2길 27-22',
    name_en: 'Hongdae Bao Branch', description_en: 'Hongik Univ. Stn Exit 9, 3 min walk', address_en: '27-22, Hongik-ro 2-gil, Mapo-gu, Seoul',
    name_ja: '弘大バオ店', description_ja: '弘大入口駅 9番出口 徒歩 3分', address_ja: 'ソウル市 麻浦区 弘益路2街 27-22',
    name_zh: '弘大Bao店', description_zh: '弘益大学站 9号出口 步行 3分钟', address_zh: '首尔市 麻浦区 弘益路2街 27-22',
    pickupGuide_en: 'Hongdae Bao Branch (Near Hongik Univ. Exit 9), please visit the counter.',
    pickupGuide_ja: '弘大バ오店(弘大入口駅9번出口付近) カウンターへお越しください。',
    pickupGuide_zh: '请访问弘大Bao店(弘大入口站9号出口附近)柜台。',
    businessHours: '10:00 - 22:00',
    businessHours_en: '10:00 - 22:00',
    businessHours_ja: '10:00 - 22:00',
    businessHours_zh: '10:00 - 22:00',
    supportsDelivery: true, supportsStorage: true, lat: 37.555547, lng: 126.92446,
    isActive: true, isPartner: true
  },
  {
    id: 'MYN', shortCode: 'MYN', name: '연남점', type: LocationType.PARTNER,
    description: '홍대입구역 3번 출구 도보 2분', address: '월드컵북로2길 93',
    name_en: 'Yeonnam Branch', description_en: 'Hongik Univ. Stn Exit 3, 2 min walk', address_en: '93, World Cup buk-ro 2-gil, Mapo-gu, Seoul',
    name_ja: '延南店', description_ja: '弘대入口駅 3番出口 徒歩 2分', address_ja: 'ソウル市 麻浦区 ワールドカップ北路2キル 93',
    name_zh: '延南店', description_zh: '弘益大学站 3号出口 步行 2分钟', address_zh: '首尔市 麻浦区 世界杯北路2街 93',
    pickupGuide_en: 'Money Box Yeonnam Branch, please visit the counter.',
    pickupGuide_ja: 'マネーボックス 延南店、カウンターへお越しください。',
    pickupGuide_zh: '请访问Money Box延南店柜台。',
    businessHours: '10:00 - 21:00',
    businessHours_en: '10:00 - 21:00',
    businessHours_ja: '10:00 - 21:00',
    businessHours_zh: '10:00 - 21:00',
    supportsDelivery: true, supportsStorage: true, lat: 37.5615, lng: 126.9255,
    isActive: true, isPartner: true
  },
  {
    id: 'MDD', shortCode: 'MDD', name: '동대문점', type: LocationType.PARTNER,
    description: '동대문역 도보 3분', address: '장충단로 281',
    name_en: 'Dongdaemun Branch', description_en: 'Dongdaemun Stn, 3 min walk', address_en: '281, Jangchungdan-ro, Jung-gu, Seoul',
    name_ja: '東大門店', description_ja: '東大門駅 徒歩 3分', address_ja: 'ソウル市 中区 奨忠壇路 281',
    name_zh: '东大门店', description_zh: '东大门站 步行 3分钟', address_zh: '首尔市 中区 奖忠坛路 281',
    pickupGuide_en: 'Dongdaemun Branch counter, please mention Beeliber.',
    pickupGuide_ja: '東大門店カウンターでBeeliberの予約をお伝えください。',
    pickupGuide_zh: '请在东大门店柜台告知您的Beeliber预订。',
    businessHours: '10:00 - 21:00',
    businessHours_en: '10:00 - 21:00',
    businessHours_ja: '10:00 - 21:00',
    businessHours_zh: '10:00 - 21:00',
    supportsDelivery: true, supportsStorage: true, lat: 37.5665, lng: 127.0092,
    isActive: false
  },
  {
    id: 'MGN', shortCode: 'MGN', name: '강남역점', type: LocationType.PARTNER,
    description: '강남역 10번 출구 도보 5분', address: '서초대로77길 3',
    name_en: 'Gangnam Stn Branch', description_en: 'Gangnam Stn Exit 10, 5 min walk', address_en: '3, Seocho-daero 77-gil, Seocho-gu, Seoul',
    name_ja: '江南駅店', description_ja: '江南駅 10番出口 徒歩 5分', address_ja: 'ソウル市 瑞草区 瑞草大路77キル 3',
    name_zh: '江南站店', description_zh: '江南站 10号出口 步行 5分钟', address_zh: '首尔市 瑞草区 瑞草大路77街 3',
    pickupGuide_en: 'Gangnam Branch counter, inside the building.',
    pickupGuide_ja: '江南駅店、建物内のカウンターをご利用ください。',
    pickupGuide_zh: '请访问江南站店，位于建筑物内部柜台。',
    businessHours: '10:00 - 22:00',
    businessHours_en: '10:00 - 22:00',
    businessHours_ja: '10:00 - 22:00',
    businessHours_zh: '10:00 - 22:00',
    supportsDelivery: true, supportsStorage: true, lat: 37.5012, lng: 127.0256,
    isActive: false
  },
  {
    id: 'MSIS', shortCode: 'MSIS', name: '강남 신사점', type: LocationType.PARTNER,
    description: '신사역 8번 출구 도보 3분', address: '도산대로 127',
    name_en: 'Gangnam Sinsa Branch', description_en: 'Sinsa Stn Exit 8, 3 min walk', address_en: '127, Dosan-daero, Gangnam-gu, Seoul',
    name_ja: '江南新沙店', description_ja: '新沙駅 8番出口 徒歩 3分', address_ja: 'ソウル市 江南区 島山大路 127',
    name_zh: '江南新沙店', description_zh: '新沙站 8号出口 步行 3分钟', address_zh: '首尔市 江南区 岛山大路 127',
    pickupGuide_en: 'Sinsa Branch counter, near the main street.',
    pickupGuide_ja: '新沙店カウンター、大通り沿いにあります。',
    pickupGuide_zh: '请访问新沙店柜台，位于主干道附近。',
    businessHours: '10:00 - 21:00',
    businessHours_en: '10:00 - 21:00',
    businessHours_ja: '10:00 - 21:00',
    businessHours_zh: '10:00 - 21:00',
    supportsDelivery: true, supportsStorage: true, lat: 37.5195, lng: 127.0224,
    isActive: false
  },
  {
    id: 'MSUS', shortCode: 'MSUS', name: '성수역점', type: LocationType.PARTNER,
    description: '성수역 3번 출구 도보 5분', address: '연무장5가길 16',
    name_en: 'Seongsu Branch', description_en: 'Seongsu Stn Exit 3, 5 min walk', address_en: '16, Yeonmujang 5-ga-gil, Seongdong-gu, Seoul',
    name_ja: '聖水駅店', description_ja: '聖水駅 3番出口 徒歩 5分', address_ja: 'ソウル市 城東区 演武場5カキル 16',
    name_zh: '圣水站店', description_zh: '圣水站 3号出口 步行 5分钟', address_zh: '首尔市 城东区 演武场5街 16',
    pickupGuide_en: 'Seongsu Branch counter, near the cafe street.',
    pickupGuide_ja: '聖水店カウンター、カフェ通りの近くにあります。',
    pickupGuide_zh: '请访问圣水店柜台，位于咖啡街附近。',
    businessHours: '10:00 - 22:00',
    businessHours_en: '10:00 - 22:00',
    businessHours_ja: '10:00 - 22:00',
    businessHours_zh: '10:00 - 22:00',
    supportsDelivery: true, supportsStorage: true, lat: 37.5435, lng: 127.0561,
    isActive: false
  },
  {
    id: 'MYS', shortCode: 'MYS', name: '서울 드래곤 시티점', type: LocationType.PARTNER,
    description: '용산역 연결 통로 도보 7분', address: '청파로20길 95',
    name_en: 'Seoul Dragon City Branch', description_en: 'Connected to Yongsan Stn, 7 min walk', address_en: '95, Cheongpa-ro 20-gil, Yongsan-gu, Seoul',
    name_ja: 'ソウルドラゴンシティ店', description_ja: '龍山駅 連結通路 徒歩 7分', address_ja: 'ソウル市 龍山区 青坡路20キル 95',
    name_zh: '首尔龙城店', description_zh: '龙山站 连接通道 步行 7分钟', address_zh: '首尔市 龙山区 青坡路20街 95',
    pickupGuide_en: 'Dragon City Hotel Branch, inside Money Box.',
    pickupGuide_ja: 'ドラゴンシティ店、マネーボックスのカウンターへお越しください。',
    pickupGuide_zh: '请访问龙城酒店内Money Box柜台。',
    businessHours: '10:00 - 22:00',
    businessHours_en: '10:00 - 22:00',
    businessHours_ja: '10:00 - 22:00',
    businessHours_zh: '10:00 - 22:00',
    supportsDelivery: true, supportsStorage: true, lat: 37.5292, lng: 126.9647,
    isActive: false
  }
];

export const NAV_LINKS = [
  { name: '서비스 소개', href: '#services' },
  { name: '지점 안내', href: '#locations' },
  { name: '배송 조회', href: '#tracking' },
  { name: '제휴 문의', href: '#partners' },
];
