
import { LocationOption, LocationType } from "./types";

export const LOCATIONS: LocationOption[] = [
  // Airports
  {
    id: 'IN1T', shortCode: 'IN1T', name: '인천공항 T1', type: LocationType.AIRPORT,
    description: '3층 출국장 A 카운터', address: '인천광역시 중구 공항로 270',
    name_en: 'Incheon Airport T1', description_en: '3F Departure Hall A Counter', address_en: '270, Gonghang-ro, Jung-gu, Incheon',
    name_ja: '仁川空港 T1', description_ja: '3階 出発ロビー Aカウンター', address_ja: '仁川広域市 中区 空港路 270',
    name_zh: '仁川机场 T1', description_zh: '3楼 出境大厅 A 柜台', address_zh: '仁川广域市 中区 机场路 270',
    name_zh_tw: '仁川機場 T1', description_zh_tw: '3樓 出境大廳 A 櫃台', address_zh_tw: '仁川廣域市 中區 機場路 270',
    name_zh_hk: '仁川機場 T1', description_zh_hk: '3樓 出境大廳 A 櫃台', address_zh_hk: '仁川廣域市 中區 機場路 270',
    pickupGuide_en: '3F Departure Hall A counter, look for the yellow Beeliber sign.',
    pickupGuide_ja: '3階 出発ロビー Aカウンター、黄色のBeeliber의看板を探してください。',
    pickupGuide_zh: '请在3楼出境大厅A柜台前寻找黄色的Beeliber标志。',
    pickupGuide_zh_tw: '請在3樓出境大廳A櫃台前尋找黃色的Beeliber標誌。',
    pickupGuide_zh_hk: '請在3樓出境大廳A櫃台前尋找黃色的Beeliber標誌。',
    businessHours: '07:00 - 22:00',
    businessHours_en: '07:00 - 22:00',
    businessHours_ja: '07:00 - 22:00',
    businessHours_zh: '07:00 - 22:00',
    supportsDelivery: true, supportsStorage: false, lat: 37.4485, lng: 126.4525,
    originSurcharge: 3000, destinationSurcharge: 3000,
    isActive: true
  },
  {
    id: 'IN2T', shortCode: 'IN2T', name: '인천공항 T2', type: LocationType.AIRPORT,
    description: '3층 출국장 H 카운터', address: '인천광역시 중구 제2터미널대로 446',
    name_en: 'Incheon Airport T2', description_en: '3F Departure Hall H Counter', address_en: '446, Je2terminal-daero, Jung-gu, Incheon',
    name_ja: '仁川空港 T2', description_ja: '3階 出発ロビー Hカウンター', address_ja: '仁川広域市 中区 第2터미널大路 446',
    name_zh: '仁川机场 T2', description_zh: '3楼 出境大厅 H 柜台', address_zh: '仁川广域市 中区 第2航站楼大路 446',
    name_zh_tw: '仁川機場 T2', description_zh_tw: '3樓 出境大廳 H 櫃台', address_zh_tw: '仁川廣域市 中區 第2航廈大路 446',
    name_zh_hk: '仁川機場 T2', description_zh_hk: '3樓 出境大廳 H 櫃台', address_zh_hk: '仁川廣域市 中區 第2航廈大路 446',
    pickupGuide_en: '3F Departure Hall H Counter, meet our staff with the Beeliber vest.',
    pickupGuide_ja: '3階 出発ロビー Hカウンター、Beeliber의ベストを着用したスタッフ과 만나세요.',
    pickupGuide_zh: '请在3楼出境大厅H柜台前与我们的工作人员会面。',
    pickupGuide_zh_tw: '請在3樓出境大廳H櫃台前與我們的工作人員會面。',
    pickupGuide_zh_hk: '請在3樓出境大廳H櫃台前與我們的工作人員會面。',
    businessHours: '07:00 - 22:00',
    businessHours_en: '07:00 - 22:00',
    businessHours_ja: '07:00 - 22:00',
    businessHours_zh: '07:00 - 22:00',
    supportsDelivery: true, supportsStorage: false, lat: 37.4687, lng: 126.4344,
    originSurcharge: 3000, destinationSurcharge: 3000,
    isActive: true
  },
  {
    id: 'GMP', shortCode: 'GMP', name: '김포공항', type: LocationType.AIRPORT,
    description: '국제선 1층 입국장 수화물 보관소', address: '서울시 강서구 하늘길 111',
    name_en: 'Gimpo Airport', description_en: 'Intl Terminal 1F Arrival Baggage Storage', address_en: '111, Haneul-gil, Gangseo-gu, Seoul',
    name_ja: '金浦空港', description_ja: '国際線 1階 到着ロビー 手荷물保管所', address_ja: 'ソウル市 江西区 ハヌルギル 111',
    name_zh: '金浦机场', description_zh: '国际线 1楼 入境大厅 行李寄存处', address_zh: '首尔市 江西区 天空路 111',
    name_zh_tw: '金浦機場', description_zh_tw: '國際線 1樓 入境大廳 行李寄存處', address_zh_tw: '首爾市 江西區 天空路 111',
    name_zh_hk: '金浦機場', description_zh_hk: '國際線 1樓 入境大廳 行李寄存處', address_zh_hk: '首爾市 江西區 天空路 111',
    pickupGuide_en: 'Intl Terminal 1F Arrival, drop off at "Left Baggage" storage.',
    pickupGuide_ja: '国際線 1階 到着ロビー 手荷物保管所(Left Baggage)にお預けください。',
    pickupGuide_zh: '请寄存在金浦机场国际线1楼入境大厅行李寄存处(Left Baggage)。',
    pickupGuide_zh_tw: '請寄存在金浦機場國際線1樓入境大廳行李寄存處(Left Baggage)。',
    pickupGuide_zh_hk: '請寄存在金浦機場國際線1樓入境大廳行李寄存處(Left Baggage)。',
    businessHours: '07:00 - 22:00',
    businessHours_en: '07:00 - 22:00',
    businessHours_ja: '07:00 - 22:00',
    businessHours_zh: '07:00 - 22:00',
    supportsDelivery: true, supportsStorage: false, lat: 37.5596, lng: 126.7940,
    originSurcharge: 2000, destinationSurcharge: 2000,
    isActive: true
  },

  // City Branches (Partners)
  {
    id: 'HBO', shortCode: 'HBO', name: '홍대 바오점', type: LocationType.PARTNER,
    description: '홍대입구역 9번 출구 도보 3분', address: '홍익로2길 27-22',
    name_en: 'Hongdae Bao Branch', description_en: 'Hongik Univ. Stn Exit 9, 3 min walk', address_en: '27-22, Hongik-ro 2-gil, Mapo-gu, Seoul',
    name_ja: '弘大バオ店', description_ja: '弘大入口駅 9番出口 徒歩 3分', address_ja: 'ソウル市 麻浦区 弘益路2街 27-22',
    name_zh: '弘大Bao店', description_zh: '弘益大学站 9号出口 步行 3分钟', address_zh: '首尔市 麻浦区 弘益路2街 27-22',
    name_zh_tw: '弘大Bao店', description_zh_tw: '弘益大學站 9號出口 步行 3分鐘', address_zh_tw: '首爾市 麻浦區 弘益路2街 27-22',
    name_zh_hk: '弘大Bao店', description_zh_hk: '弘益大學站 9號出口 步行 3分鐘', address_zh_hk: '首爾市 麻浦區 弘益路2街 27-22',
    pickupGuide_en: 'Hongdae Bao Branch (Near Hongik Univ. Exit 9), please visit the counter.',
    pickupGuide_ja: '弘大バオ店(弘大入口駅9番出口付近) カウンターへお越しください。',
    pickupGuide_zh: '请访问弘大Bao店(弘大入口站9号出口附近)柜台。',
    pickupGuide_zh_tw: '請前往弘大Bao店(弘大入口站9號出口附近)櫃台。',
    pickupGuide_zh_hk: '請前往弘大Bao店(弘大入口站9號出口附近)櫃台。',
    businessHours: '10:00 - 22:00',
    businessHours_en: '10:00 - 22:00',
    businessHours_ja: '10:00 - 22:00',
    businessHours_zh: '10:00 - 22:00',
    supportsDelivery: true, supportsStorage: true, lat: 37.5555529, lng: 126.9244614,
    isActive: true, isPartner: true
  },
  {
    id: 'MYN', shortCode: 'MYN', name: '연남점', type: LocationType.PARTNER,
    description: '홍대입구역 3번 출구 도보 2분', address: '월드컵북로2길 93',
    name_en: 'Yeonnam Branch', description_en: 'Hongik Univ. Stn Exit 3, 2 min walk', address_en: '93, World Cup buk-ro 2-gil, Mapo-gu, Seoul',
    name_ja: '延南店', description_ja: '弘대入口駅 3番出口 徒歩 2分', address_ja: 'ソウル市 麻浦区 ワールドカップ北路2キル 93',
    name_zh: '延南店', description_zh: '弘益大学站 3号出口 步行 2分钟', address_zh: '首尔市 麻浦区 世界杯北路2街 93',
    name_zh_tw: '延南店', description_zh_tw: '弘益大學站 3號出口 步行 2分鐘', address_zh_tw: '首爾市 麻浦區 世界杯北路2街 93',
    name_zh_hk: '延南店', description_zh_hk: '弘益大學站 3號出口 步行 2分鐘', address_zh_hk: '首爾市 麻浦區 世界杯北路2街 93',
    pickupGuide_en: 'Money Box Yeonnam Branch, please visit the counter.',
    pickupGuide_ja: 'マネーボックス 延南店、カウンターへお越しください。',
    pickupGuide_zh: '请访问Money Box延南店柜台。',
    businessHours: '10:00 - 21:00',
    businessHours_en: '10:00 - 21:00',
    businessHours_ja: '10:00 - 21:00',
    businessHours_zh: '10:00 - 21:00',
    supportsDelivery: true, supportsStorage: true, lat: 37.5587971, lng: 126.9248631,
    isActive: true, isPartner: true
  },
  {
    id: 'MDD', shortCode: 'MDD', name: '동대문점', type: LocationType.PARTNER,
    description: '동대문역 도보 3분', address: '장충단로 281',
    name_en: 'Dongdaemun Branch', description_en: 'Dongdaemun Stn, 3 min walk', address_en: '281, Jangchungdan-ro, Jung-gu, Seoul',
    name_ja: '東大門店', description_ja: '東大門駅 徒歩 3分', address_ja: 'ソウル市 中区 奨忠壇路 281',
    name_zh: '东大门店', description_zh: '东大门站 步行 3分钟', address_zh: '首尔市 中区 奖忠坛路 281',
    name_zh_tw: '東大門店', description_zh_tw: '東大門站 步行 3分鐘', address_zh_tw: '首爾市 中區 獎忠壇路 281',
    name_zh_hk: '東大門店', description_zh_hk: '東大門站 步行 3分鐘', address_zh_hk: '首爾市 中區 獎忠壇路 281',
    pickupGuide_en: 'Dongdaemun Branch counter, please mention Beeliber.',
    pickupGuide_ja: '東大門店カウンターでBeeliberの予約をお伝えください。',
    pickupGuide_zh: '请在东大门店柜台告知您的Beeliber预订。',
    pickupGuide_zh_tw: '請在東大門店櫃台告知您的Beeliber預訂。',
    pickupGuide_zh_hk: '請在東大門店櫃台告知您的Beeliber預訂。',
    businessHours: '10:00 - 21:00',
    businessHours_en: '10:00 - 21:00',
    businessHours_ja: '10:00 - 21:00',
    businessHours_zh: '10:00 - 21:00',
    supportsDelivery: true, supportsStorage: true, lat: 37.5665, lng: 127.0092,
    isActive: false
  },
  {
    id: 'MGH', shortCode: 'MGH', name: '광장시장점', type: LocationType.PARTNER,
    description: '종로5가역 8번 출구 도보 2분', address: '종로 210',
    name_en: 'Gwangjang Market Branch', description_en: 'Jongno 5-ga Stn Exit 8, 2 min walk', address_en: '210, Jong-ro, Jongno-gu, Seoul',
    name_ja: '広蔵市場店', description_ja: '鍾路5街駅 8番出口 徒歩 2分', address_ja: 'ソウル市 鍾路区 鍾路 210',
    name_zh: '广藏市场店', description_zh: '钟路5街站 8号出口 步行 2分钟', address_zh: '首尔市 钟路区 钟路 210',
    name_zh_tw: '廣藏市場店', description_zh_tw: '鐘路5街站 8號出口 步行 2分鐘', address_zh_tw: '首爾市 鐘路區 鐘路 210',
    name_zh_hk: '廣藏市場店', description_zh_hk: '鐘路5街站 8號出口 步行 2分鐘', address_zh_hk: '首爾市 鐘路區 鐘路 210',
    pickupGuide_en: 'Gwangjang Market Branch, please visit the counter.',
    pickupGuide_ja: '広蔵市場店カウンターへお越しください。',
    pickupGuide_zh: '请访问广藏市场店柜台。',
    pickupGuide_zh_tw: '請訪問廣藏市場店櫃台。',
    pickupGuide_zh_hk: '請訪問廣藏市場店櫃台。',
    businessHours: '10:00 - 21:00',
    businessHours_en: '10:00 - 21:00',
    businessHours_ja: '10:00 - 21:00',
    businessHours_zh: '10:00 - 21:00',
    supportsDelivery: true, supportsStorage: true, lat: 37.5709, lng: 126.9985,
    isActive: false
  },
  {
    id: 'MMP', shortCode: 'MMP', name: '마포지점', type: LocationType.PARTNER,
    description: '마포역 3번 출구 도보 1분', address: '마포대로 68',
    name_en: 'Mapo Branch', description_en: 'Mapo Stn Exit 3, 1 min walk', address_en: '68, Mapo-daero, Mapo-gu, Seoul',
    name_ja: '麻浦店', description_ja: '麻浦駅 3番出口 徒歩 1分', address_ja: 'ソウル市 麻浦区 麻浦大路 68',
    name_zh: '麻浦店', description_zh: '麻浦站 3号出口 步行 1分钟', address_zh: '首尔市 麻浦区 麻浦大路 68',
    name_zh_tw: '麻浦店', description_zh_tw: '麻浦站 3號出口 步行 1分鐘', address_zh_tw: '首爾市 麻浦區 麻浦大路 68',
    name_zh_hk: '麻浦店', description_zh_hk: '麻浦站 3號出口 步行 1分鐘', address_zh_hk: '首爾市 麻浦區 麻浦大路 68',
    pickupGuide_en: 'Mapo Branch, please visit the counter.',
    pickupGuide_ja: '麻浦店カウンターへお越しください。',
    pickupGuide_zh: '请访问麻浦店柜台。',
    pickupGuide_zh_tw: '請訪問麻浦店櫃台。',
    pickupGuide_zh_hk: '請訪問麻浦店櫃台。',
    businessHours: '10:00 - 21:00',
    businessHours_en: '10:00 - 21:00',
    businessHours_ja: '10:00 - 21:00',
    businessHours_zh: '10:00 - 21:00',
    supportsDelivery: true, supportsStorage: true, lat: 37.5398, lng: 126.9452,
    isActive: false
  },
  {
    id: 'MGN', shortCode: 'MGN', name: '강남역점', type: LocationType.PARTNER,
    description: '강남역 10번 출구 도보 5분', address: '서초대로77길 3',
    name_en: 'Gangnam Stn Branch', description_en: 'Gangnam Stn Exit 10, 5 min walk', address_en: '3, Seocho-daero 77-gil, Seocho-gu, Seoul',
    name_ja: '江南駅店', description_ja: '江南駅 10番出口 徒歩 5分', address_ja: 'ソウル市 瑞草区 瑞草大路77キル 3',
    name_zh: '江南站店', description_zh: '江南站 10号出口 步行 5分钟', address_zh: '首尔市 瑞草区 瑞草大路77街 3',
    pickupGuide_en: 'Gangnam Branch counter, inside the building.',
    pickupGuide_ja: '江南駅店、建物内のカウンターをご利用ください。',
    pickupGuide_zh: '请访问江南站店，位于建筑物内部柜台。',
    businessHours: '10:00 - 22:00',
    businessHours_en: '10:00 - 22:00',
    businessHours_ja: '10:00 - 22:00',
    businessHours_zh: '10:00 - 22:00',
    supportsDelivery: true, supportsStorage: true, lat: 37.5012, lng: 127.0256,
    isActive: false
  },
  {
    id: 'MSIS', shortCode: 'MSIS', name: '강남 신사점', type: LocationType.PARTNER,
    description: '신사역 8번 출구 도보 3분', address: '도산대로 127',
    name_en: 'Gangnam Sinsa Branch', description_en: 'Sinsa Stn Exit 8, 3 min walk', address_en: '127, Dosan-daero, Gangnam-gu, Seoul',
    name_ja: '江南新沙店', description_ja: '新沙駅 8番出口 徒歩 3分', address_ja: 'ソウル市 江南区 島山大路 127',
    name_zh: '江南新沙店', description_zh: '新沙站 8号出口 步行 3分钟', address_zh: '首尔市 江南区 岛山大路 127',
    pickupGuide_en: 'Sinsa Branch counter, near the main street.',
    pickupGuide_ja: '新沙店カウンター、大通り沿いにあります。',
    pickupGuide_zh: '请访问新沙店柜台，位于主干道附近。',
    businessHours: '10:00 - 21:00',
    businessHours_en: '10:00 - 21:00',
    businessHours_ja: '10:00 - 21:00',
    businessHours_zh: '10:00 - 21:00',
    supportsDelivery: true, supportsStorage: true, lat: 37.5195, lng: 127.0224,
    isActive: false
  },
  {
    id: 'MSUS', shortCode: 'MSUS', name: '성수역점', type: LocationType.PARTNER,
    description: '성수역 3번 출구 도보 5분', address: '연무장5가길 16',
    name_en: 'Seongsu Branch', description_en: 'Seongsu Stn Exit 3, 5 min walk', address_en: '16, Yeonmujang 5-ga-gil, Seongdong-gu, Seoul',
    name_ja: '聖水駅店', description_ja: '聖水駅 3番出口 徒歩 5分', address_ja: 'ソウル市 城東区 演武場5カキル 16',
    name_zh: '圣水站店', description_zh: '圣水站 3号出口 步行 5分钟', address_zh: '首尔市 城东区 演武场5街 16',
    pickupGuide_en: 'Seongsu Branch counter, near the cafe street.',
    pickupGuide_ja: '聖水店カウンター、カフェ通りの近くにあります。',
    pickupGuide_zh: '请访问圣水店柜台，位于咖啡街附近。',
    businessHours: '10:00 - 22:00',
    businessHours_en: '10:00 - 22:00',
    businessHours_ja: '10:00 - 22:00',
    businessHours_zh: '10:00 - 22:00',
    supportsDelivery: true, supportsStorage: true, lat: 37.5435, lng: 127.0561,
    isActive: false
  },
  {
    id: 'MYS', shortCode: 'MYS', name: '서울 드래곤 시티점', type: LocationType.PARTNER,
    description: '용산역 연결 통로 도보 7분', address: '청파로20길 95',
    name_en: 'Seoul Dragon City Branch', description_en: 'Connected to Yongsan Stn, 7 min walk', address_en: '95, Cheongpa-ro 20-gil, Yongsan-gu, Seoul',
    name_ja: 'ソウルドラゴンシティ店', description_ja: '龍山駅 連結通路 徒歩 7分', address_ja: 'ソウル市 龍山区 青坡路20キル 95',
    name_zh: '首尔龙城店', description_zh: '龙山站 连接通道 步行 7分钟', address_zh: '首尔市 龙山区 青坡路20街 95',
    name_zh_tw: '首爾龍城店', description_zh_tw: '龍山站 連接通道 步行 7分鐘', address_zh_tw: '首爾市 龍山區 青坡路20街 95',
    name_zh_hk: '首爾龍城店', description_zh_hk: '龍山站 連接通道 步行 7分鐘', address_zh_hk: '首爾市 龍山區 青坡路20街 95',
    pickupGuide_en: 'Dragon City Hotel Branch, inside Money Box.',
    pickupGuide_ja: 'ドラゴンシティ店、マネーボックスのカウンターへお越しください。',
    pickupGuide_zh: '请访问龙城酒店内Money Box柜台。',
    pickupGuide_zh_tw: '請訪問龍城酒店內Money Box櫃台。',
    pickupGuide_zh_hk: '請訪問龍城酒店內Money Box櫃台。',
    businessHours: '10:00 - 22:00',
    businessHours_en: '10:00 - 22:00',
    businessHours_ja: '10:00 - 22:00',
    businessHours_zh: '10:00 - 22:00',
    supportsDelivery: true, supportsStorage: true, lat: 37.5292, lng: 126.9647,
    isActive: false
  },
  {
    id: 'MIT', shortCode: 'MIT', name: '이태원지점', type: LocationType.PARTNER,
    description: '이태원역 3번 출구 도보 5분', address: '서울시 용산구 보광로 126',
    name_en: 'Itaewon Branch', description_en: 'Itaewon Stn Exit 3, 5 min walk', address_en: '126, Bogwang-ro, Yongsan-gu, Seoul',
    name_ja: '梨泰院店', description_ja: '梨泰院駅 3番出口 徒歩 5分', address_ja: 'ソウル市 龍山区 普光路 126',
    name_zh: '梨泰院店', description_zh: '梨泰院站 3号出口 步行 5分钟', address_zh: '首尔市 龙山区 普光路 126',
    name_zh_tw: '梨泰院店', description_zh_tw: '梨泰院站 3號出口 步行 5分鐘', address_zh_tw: '首爾市 龍山區 普光路 126',
    name_zh_hk: '梨泰院店', description_zh_hk: '梨泰院站 3號出口 步行 3分鐘', address_zh_hk: '首爾市 龍山區 普光路 126',
    pickupGuide: '이태원역 3번 출구 나와서 보광로 방향으로 도보 5분, 비리버 이태원지점 간판을 찾으세요.',
    pickupGuide_en: 'Exit Itaewon Station (Exit 3) and walk toward Bogwang-ro for 5 minutes. Look for the Beeliber Itaewon Branch sign.',
    pickupGuide_ja: '梨泰院駅 3番出口を出て、普光路方向へ徒歩5分。Beeliber梨泰院店の看板を探してください。',
    pickupGuide_zh: '从梨泰院站3号出口出来沿普光路步行5分钟，寻找Beeliber梨泰院店招牌。',
    pickupGuide_zh_tw: '從梨泰院站3號出口出來沿普光路步行5分鐘，尋找Beeliber梨泰院店招牌。',
    pickupGuide_zh_hk: '從梨泰院站3號出口出來沿普光路步行5分鐘，尋找Beeliber梨泰院店招牌。',
    businessHours: '10:00 - 22:00',
    businessHours_en: '10:00 - 22:00',
    businessHours_ja: '10:00 - 22:00',
    businessHours_zh: '10:00 - 22:00',
    supportsDelivery: true, supportsStorage: true, lat: 37.5340, lng: 126.9946,
    isActive: true, isPartner: true
  },
  {
    id: 'MBX-001', shortCode: 'MBX-001', name: '안국역지점', type: LocationType.PARTNER,
    description: '연락처: 02-766-8887', address: '서울시 종로구 율곡로 65',
    name_en: 'Anguk Station Branch', address_en: '65 Yulgok-ro, Jongno-gu, Seoul',
    name_ja: '安国駅店', address_ja: 'ソウル特別市鐘路区栗谷路65',
    name_zh: '安国站店', address_zh: '首尔特别市钟路区栗谷路65',
        name_zh_tw: '安國站店',
    name_zh_hk: '安國站店',
    address_zh_tw: '首爾特別市鐘路區栗谷路65',
    address_zh_hk: '首爾特別市鐘路區栗谷路65',
    pickupGuide_en: 'Branch counter, please visit inside and mention Beeliber.',
    pickupGuide_ja: 'カウンターにお越しいただき、Beeliberの予約をお伝えください。',
    pickupGuide_zh: '请前往柜台告知您的Beeliber预订。',
    pickupGuide_zh_tw: '請前往櫃台告知您的Beeliber預訂。',
    pickupGuide_zh_hk: '請前往櫃台告知您的Beeliber預訂。',
    businessHours_en: '09:00 - 21:00',
    businessHours_ja: '09:00 - 21:00',
    businessHours_zh: '09:00 - 21:00',
businessHours: '09:00 - 21:00',
    supportsDelivery: true, supportsStorage: true,
    isOrigin: true, isDestination: true,
    isPartner: true, isActive: false, lat: 37.5759, lng: 126.9841
  },
  {
    id: 'MBX-002', shortCode: 'MBX-002', name: '동대문DDP점', type: LocationType.PARTNER,
    description: '연락처: 02-2278-7888', address: '서울시 중구 장충단로13길 13',
    name_en: 'Dongdaemun DDP Branch', address_en: '13 Jangchungdan-ro 13-gil, Jung-gu, Seoul',
    name_ja: '東大門DDP店', address_ja: 'ソウル特別市中区奨忠壇路13キル13',
    name_zh: '东大门DDP店', address_zh: '首尔特别市中区奖忠坛路13街13',
        name_zh_tw: '東大門DDP店',
    name_zh_hk: '東大門DDP店',
    address_zh_tw: '首爾特別市中區獎忠壇路13街13',
    address_zh_hk: '首爾特別市中區獎忠壇路13街13',
    pickupGuide_en: 'Branch counter, please visit inside and mention Beeliber.',
    pickupGuide_ja: 'カウンターにお越しいただき、Beeliberの予約をお伝えください。',
    pickupGuide_zh: '请前往柜台告知您的Beeliber预订。',
    pickupGuide_zh_tw: '請前往櫃台告知您的Beeliber預訂。',
    pickupGuide_zh_hk: '請前往櫃台告知您的Beeliber預訂。',
    businessHours_en: '09:00 - 21:00',
    businessHours_ja: '09:00 - 21:00',
    businessHours_zh: '09:00 - 21:00',
businessHours: '09:00 - 21:00',
    supportsDelivery: true, supportsStorage: true,
    isOrigin: true, isDestination: true,
    isPartner: true, isActive: false, lat: 37.566517, lng: 127.009108
  },
  {
    id: 'MBX-003', shortCode: 'MBX-003', name: '종로지점', type: LocationType.PARTNER,
    description: '연락처: 02-766-5888', address: '서울시 종로구 돈화문로 45',
    name_en: 'Jongno Branch', address_en: '45 Donhwamun-ro, Jongno-gu, Seoul',
    name_ja: '鍾路店', address_ja: 'ソウル特別市鐘路区敦化門路45',
    name_zh: '钟路店', address_zh: '首尔特别市钟路区敦化门路45',
        name_zh_tw: '鐘路店',
    name_zh_hk: '鐘路店',
    address_zh_tw: '首爾特別市鐘路區敦化門路45',
    address_zh_hk: '首爾特別市鐘路區敦化門路45',
    pickupGuide_en: 'Branch counter, please visit inside and mention Beeliber.',
    pickupGuide_ja: 'カウンターにお越しいただき、Beeliberの予約をお伝えください。',
    pickupGuide_zh: '请前往柜台告知您的Beeliber预订。',
    pickupGuide_zh_tw: '請前往櫃台告知您的Beeliber預訂。',
    pickupGuide_zh_hk: '請前往櫃台告知您的Beeliber預訂。',
    businessHours_en: '09:00 - 21:00',
    businessHours_ja: '09:00 - 21:00',
    businessHours_zh: '09:00 - 21:00',
businessHours: '09:00 - 21:00',
    supportsDelivery: true, supportsStorage: true,
    isOrigin: true, isDestination: true,
    isPartner: true, isActive: false, lat: 37.5718, lng: 126.9926
  },
  {
    id: 'MBX-004', shortCode: 'MBX-004', name: '충무로지점', type: LocationType.PARTNER,
    description: '연락처: 02-2272-8882', address: '서울시 중구 마른내로 42',
    name_en: 'Chungmuro Branch', address_en: '42 Mareunnae-ro, Jung-gu, Seoul',
    name_ja: '忠武路店', address_ja: 'ソウル特別市中区マルンネ路42',
    name_zh: '忠武路店', address_zh: '首尔特别市中区干川路42',
        name_zh_tw: '忠武路店',
    name_zh_hk: '忠武路店',
    address_zh_tw: '首爾特別市中區乾川路42',
    address_zh_hk: '首爾特別市中區乾川路42',
    pickupGuide_en: 'Branch counter, please visit inside and mention Beeliber.',
    pickupGuide_ja: 'カウンターにお越しいただき、Beeliberの予約をお伝えください。',
    pickupGuide_zh: '请前往柜台告知您的Beeliber预订。',
    pickupGuide_zh_tw: '請前往櫃台告知您的Beeliber預訂。',
    pickupGuide_zh_hk: '請前往櫃台告知您的Beeliber預訂。',
    businessHours_en: '09:00 - 21:00',
    businessHours_ja: '09:00 - 21:00',
    businessHours_zh: '09:00 - 21:00',
businessHours: '09:00 - 21:00',
    supportsDelivery: true, supportsStorage: true,
    isOrigin: true, isDestination: true,
    isPartner: true, isActive: false, lat: 37.5642, lng: 126.9925
  },
  {
    id: 'MBX-005', shortCode: 'MBX-005', name: '성수역점', type: LocationType.PARTNER,
    description: '연락처: 02-498-8898', address: '서울시 성동구 연무장5가길 16',
    name_en: 'Seongsu Station Branch', address_en: '16 Yeonmujang 5-ga-gil, Seongdong-gu, Seoul',
    name_ja: '聖水駅店', address_ja: 'ソウル特別市城東区演武場5カキル16',
    name_zh: '圣水站店', address_zh: '首尔特别市城东区演武场5街16',
        name_zh_tw: '聖水站店',
    name_zh_hk: '聖水站店',
    address_zh_tw: '首爾特別市城東區演武場5街16',
    address_zh_hk: '首爾特別市城東區演武場5街16',
    pickupGuide_en: 'Branch counter, please visit inside and mention Beeliber.',
    pickupGuide_ja: 'カウンターにお越しいただき、Beeliberの予約をお伝えください。',
    pickupGuide_zh: '请前往柜台告知您的Beeliber预订。',
    pickupGuide_zh_tw: '請前往櫃台告知您的Beeliber預訂。',
    pickupGuide_zh_hk: '請前往櫃台告知您的Beeliber預訂。',
    businessHours_en: '09:00 - 21:00',
    businessHours_ja: '09:00 - 21:00',
    businessHours_zh: '09:00 - 21:00',
businessHours: '09:00 - 21:00',
    supportsDelivery: true, supportsStorage: true,
    isOrigin: true, isDestination: true,
    isPartner: true, isActive: false, lat: 37.54311, lng: 127.05595
  },
  {
    id: 'MBX-006', shortCode: 'MBX-006', name: '강남신사점', type: LocationType.PARTNER,
    description: '연락처: 02-518-8883', address: '서울시 강남구 도산대로 127',
    name_en: 'Gangnam Sinsa Branch', address_en: '127 Dosan-daero, Gangnam-gu, Seoul',
    name_ja: '江南新沙店', address_ja: 'ソウル特別市江南区島山大路127',
    name_zh: '江南新沙店', address_zh: '首尔特别市江南区岛山大路127',
        name_zh_tw: '江南新沙店',
    name_zh_hk: '江南新沙店',
    address_zh_tw: '首爾特別市江南區島山大路127',
    address_zh_hk: '首爾特別市江南區島山大路127',
    pickupGuide_en: 'Branch counter, please visit inside and mention Beeliber.',
    pickupGuide_ja: 'カウンターにお越しいただき、Beeliberの予約をお伝えください。',
    pickupGuide_zh: '请前往柜台告知您的Beeliber预订。',
    pickupGuide_zh_tw: '請前往櫃台告知您的Beeliber預訂。',
    pickupGuide_zh_hk: '請前往櫃台告知您的Beeliber預訂。',
    businessHours_en: '09:00 - 21:00',
    businessHours_ja: '09:00 - 21:00',
    businessHours_zh: '09:00 - 21:00',
businessHours: '09:00 - 21:00',
    supportsDelivery: true, supportsStorage: true,
    isOrigin: true, isDestination: true,
    isPartner: true, isActive: false, lat: 37.51955, lng: 127.02243
  },
  {
    id: 'MBX-007', shortCode: 'MBX-007', name: '머니박스제일환전센터', type: LocationType.PARTNER,
    description: '연락처: 02-773-0000', address: '서울시 중구 남대문로 68-1',
    name_en: 'Money Box Exchange Center', address_en: '68-1 Namdaemun-ro, Jung-gu, Seoul',
    name_ja: 'マネーボックス両替', address_ja: 'ソウル特別市中区南大門路68-1',
    name_zh: 'Money Box 换钱中心', address_zh: '首尔特别市中区南大门路68-1',
        name_zh_tw: 'Money Box 換錢中心',
    name_zh_hk: 'Money Box 換錢中心',
    address_zh_tw: '首爾特別市中區南大門路68-1',
    address_zh_hk: '首爾特別市中區南大門路68-1',
    pickupGuide_en: 'Branch counter, please visit inside and mention Beeliber.',
    pickupGuide_ja: 'カウンターにお越しいただき、Beeliberの予約をお伝えください。',
    pickupGuide_zh: '请前往柜台告知您的Beeliber预订。',
    pickupGuide_zh_tw: '請前往櫃台告知您的Beeliber預訂。',
    pickupGuide_zh_hk: '請前往櫃台告知您的Beeliber預訂。',
    businessHours_en: '09:00 - 21:00',
    businessHours_ja: '09:00 - 21:00',
    businessHours_zh: '09:00 - 21:00',
businessHours: '09:00 - 21:00',
    supportsDelivery: true, supportsStorage: true,
    isOrigin: true, isDestination: true,
    isPartner: true, isActive: false, lat: 37.563319, lng: 126.982242
  },
  {
    id: 'MBX-008', shortCode: 'MBX-008', name: '여의도지점', type: LocationType.PARTNER,
    description: '연락처: 02-761-8889', address: '서울특별시 영등포구 여의나루로 42',
    name_en: 'Yeouido Branch', address_en: '42 Yeouinaru-ro, Yeongdeungpo-gu, Seoul',
    name_ja: '汝矣島店', address_ja: 'ソウル特別市永登浦区汝矣ナル路42',
    name_zh: '汝矣岛店', address_zh: '首尔特别市永登浦区汝矣渡口路42',
        name_zh_tw: '汝矣島店',
    name_zh_hk: '汝矣島店',
    address_zh_tw: '首爾特別市永登浦區汝矣渡口路42',
    address_zh_hk: '首爾特別市永登浦區汝矣渡口路42',
    pickupGuide_en: 'Branch counter, please visit inside and mention Beeliber.',
    pickupGuide_ja: 'カウンターにお越しいただき、Beeliberの予約をお伝えください。',
    pickupGuide_zh: '请前往柜台告知您的Beeliber预订。',
    pickupGuide_zh_tw: '請前往櫃台告知您的Beeliber預訂。',
    pickupGuide_zh_hk: '請前往櫃台告知您的Beeliber預訂。',
    businessHours_en: '09:00 - 21:00',
    businessHours_ja: '09:00 - 21:00',
    businessHours_zh: '09:00 - 21:00',
businessHours: '09:00 - 21:00',
    supportsDelivery: true, supportsStorage: true,
    isOrigin: true, isDestination: true,
    isPartner: true, isActive: false, lat: 37.521762, lng: 126.924896
  },
  {
    id: 'MBX-009', shortCode: 'MBX-009', name: '명동2호점', type: LocationType.PARTNER,
    description: '연락처: 02-318-8801', address: '서울시 중구 명동9길 15',
    name_en: 'Myeongdong No.2 Branch', address_en: '15 Myeongdong 9-gil, Jung-gu, Seoul',
    name_ja: '明洞2号店', address_ja: 'ソウル特別市中区明洞9キル15',
    name_zh: '明洞2号店', address_zh: '首尔特别市中区明洞9街15',
        name_zh_tw: '明洞2號店',
    name_zh_hk: '明洞2號店',
    address_zh_tw: '首爾特別市中區明洞9街15',
    address_zh_hk: '首爾特別市中區明洞9街15',
    pickupGuide_en: 'Branch counter, please visit inside and mention Beeliber.',
    pickupGuide_ja: 'カウンターにお越しいただき、Beeliberの予約をお伝えください。',
    pickupGuide_zh: '请前往柜台告知您的Beeliber预订。',
    pickupGuide_zh_tw: '請前往櫃台告知您的Beeliber預訂。',
    pickupGuide_zh_hk: '請前往櫃台告知您的Beeliber預訂。',
    businessHours_en: '09:00 - 21:00',
    businessHours_ja: '09:00 - 21:00',
    businessHours_zh: '09:00 - 21:00',
businessHours: '09:00 - 21:00',
    supportsDelivery: true, supportsStorage: true,
    isOrigin: true, isDestination: true,
    isPartner: true, isActive: false, lat: 37.5652, lng: 126.9842
  },
  {
    id: 'MBX-010', shortCode: 'MBX-010', name: '이태원지점', type: LocationType.PARTNER,
    description: '연락처: 02-749-8883', address: '서울시 용산구 이태원동 127-28',
    name_en: 'Itaewon Branch', address_en: '127-28 Itaewon-dong, Yongsan-gu, Seoul',
    name_ja: '梨泰院店', address_ja: 'ソウル特別市龍山区梨泰院洞127-28',
    name_zh: '梨泰院店', address_zh: '首尔特别市龙山区梨泰院洞127-28',
        name_zh_tw: '梨泰院店',
    name_zh_hk: '梨泰院店',
    address_zh_tw: '首爾特別市龍山區梨泰院洞127-28',
    address_zh_hk: '首爾特別市龍山區梨泰院洞127-28',
    pickupGuide_en: 'Branch counter, please visit inside and mention Beeliber.',
    pickupGuide_ja: 'カウンターにお越しいただき、Beeliberの予約をお伝えください。',
    pickupGuide_zh: '请前往柜台告知您的Beeliber预订。',
    pickupGuide_zh_tw: '請前往櫃台告知您的Beeliber預訂。',
    pickupGuide_zh_hk: '請前往櫃台告知您的Beeliber預訂。',
    businessHours_en: '09:00 - 21:00',
    businessHours_ja: '09:00 - 21:00',
    businessHours_zh: '09:00 - 21:00',
businessHours: '09:00 - 21:00',
    supportsDelivery: true, supportsStorage: true,
    isOrigin: true, isDestination: true,
    isPartner: true, isActive: false, lat: 37.5333, lng: 126.9942
  },
  {
    id: 'MBX-011', shortCode: 'MBX-011', name: '서울역지점', type: LocationType.PARTNER,
    description: '연락처: 02-706-8880', address: '서울시 용산구 한강대로 401-2 1층',
    name_en: 'Seoul Station Branch', address_en: '401-2 Hangang-daero, Yongsan-gu, Seoul',
    name_ja: 'ソウル駅店', address_ja: 'ソウル特別市龍山区漢江大路401-2',
    name_zh: '首尔站店', address_zh: '首尔特别市龙山区汉江大路401-2',
        name_zh_tw: '首爾站店',
    name_zh_hk: '首爾站店',
    address_zh_tw: '首爾特別市龍山區漢江大路401-2',
    address_zh_hk: '首爾特別市龍山區漢江大路401-2',
    pickupGuide_en: 'Branch counter, please visit inside and mention Beeliber.',
    pickupGuide_ja: 'カウンターにお越しいただき、Beeliberの予約をお伝えください。',
    pickupGuide_zh: '请前往柜台告知您的Beeliber预订。',
    pickupGuide_zh_tw: '請前往櫃台告知您的Beeliber預訂。',
    pickupGuide_zh_hk: '請前往櫃台告知您的Beeliber預訂。',
    businessHours_en: '09:00 - 21:00',
    businessHours_ja: '09:00 - 21:00',
    businessHours_zh: '09:00 - 21:00',
businessHours: '09:00 - 21:00',
    supportsDelivery: true, supportsStorage: true,
    isOrigin: true, isDestination: true,
    isPartner: true, isActive: false, lat: 37.5550, lng: 126.9720
  },
  {
    id: 'MBX-012', shortCode: 'MBX-012', name: '강남역지점', type: LocationType.PARTNER,
    description: '연락처: 02-3478-8388', address: '서울시 서초구 서초대로77길 3 아라타워 103호',
    name_en: 'Gangnam Station Branch', address_en: '#103 Ara Tower, 3 Seocho-daero 77-gil, Seocho-gu, Seoul',
    name_ja: '江南駅店', address_ja: 'ソウル特別市瑞草区瑞草大路77キル3',
    name_zh: '江南站店', address_zh: '首尔特别市瑞草区瑞草大路77街3',
        name_zh_tw: '江南站店',
    name_zh_hk: '江南站店',
    address_zh_tw: '首爾特別市瑞草區瑞草大路77街3',
    address_zh_hk: '首爾特別市瑞草區瑞草大路77街3',
    pickupGuide_en: 'Branch counter, please visit inside and mention Beeliber.',
    pickupGuide_ja: 'カウンターにお越しいただき、Beeliberの予約をお伝えください。',
    pickupGuide_zh: '请前往柜台告知您的Beeliber预订。',
    pickupGuide_zh_tw: '請前往櫃台告知您的Beeliber預訂。',
    pickupGuide_zh_hk: '請前往櫃台告知您的Beeliber預訂。',
    businessHours_en: '09:00 - 21:00',
    businessHours_ja: '09:00 - 21:00',
    businessHours_zh: '09:00 - 21:00',
businessHours: '09:00 - 21:00',
    supportsDelivery: true, supportsStorage: true,
    isOrigin: true, isDestination: true,
    isPartner: true, isActive: false, lat: 37.4986, lng: 127.0263
  },
  {
    id: 'MBX-013', shortCode: 'MBX-013', name: '남대문지점', type: LocationType.PARTNER,
    description: '연락처: 02-3789-8588', address: '서울시 중구 남대문시장길 73',
    name_en: 'Namdaemun Branch', address_en: '73 Namdaemunsijang-gil, Jung-gu, Seoul',
    name_ja: '南大門店', address_ja: 'ソウル特別市中区南大門市場キル73',
    name_zh: '南大门店', address_zh: '首尔特别市中区南大门市场街73',
        name_zh_tw: '南大門店',
    name_zh_hk: '南大門店',
    address_zh_tw: '首爾特別市中區南大門市場街73',
    address_zh_hk: '首爾特別市中區南大門市場街73',
    pickupGuide_en: 'Branch counter, please visit inside and mention Beeliber.',
    pickupGuide_ja: 'カウンターにお越しいただき、Beeliberの予約をお伝えください。',
    pickupGuide_zh: '请前往柜台告知您的Beeliber预订。',
    pickupGuide_zh_tw: '請前往櫃台告知您的Beeliber預訂。',
    pickupGuide_zh_hk: '請前往櫃台告知您的Beeliber預訂。',
    businessHours_en: '09:00 - 21:00',
    businessHours_ja: '09:00 - 21:00',
    businessHours_zh: '09:00 - 21:00',
businessHours: '09:00 - 21:00',
    supportsDelivery: true, supportsStorage: true,
    isOrigin: true, isDestination: true,
    isPartner: true, isActive: false, lat: 37.5592, lng: 126.9777
  },
  {
    id: 'MBX-014', shortCode: 'MBX-014', name: '인사동지점', type: LocationType.PARTNER,
    description: '연락처: 02-738-0888', address: '서울특별시 종로구 인사동4길 1',
    name_en: 'Insadong Branch', address_en: '1 Insadong 4-gil, Jongno-gu, Seoul',
    name_ja: '仁寺洞店', address_ja: 'ソウル特別市鐘路区仁寺洞4キル1',
    name_zh: '仁寺洞店', address_zh: '首尔特别市钟路区仁寺洞4街1',
        name_zh_tw: '仁寺洞店',
    name_zh_hk: '仁寺洞店',
    address_zh_tw: '首爾特別市鐘路區仁寺洞4街1',
    address_zh_hk: '首爾特別市鐘路區仁寺洞4街1',
    pickupGuide_en: 'Branch counter, please visit inside and mention Beeliber.',
    pickupGuide_ja: 'カウンターにお越しいただき、Beeliberの予約をお伝えください。',
    pickupGuide_zh: '请前往柜台告知您的Beeliber预订。',
    pickupGuide_zh_tw: '請前往櫃台告知您的Beeliber預訂。',
    pickupGuide_zh_hk: '請前往櫃台告知您的Beeliber預訂。',
    businessHours_en: '09:00 - 21:00',
    businessHours_ja: '09:00 - 21:00',
    businessHours_zh: '09:00 - 21:00',
businessHours: '09:00 - 21:00',
    supportsDelivery: true, supportsStorage: true,
    isOrigin: true, isDestination: true,
    isPartner: true, isActive: false, lat: 37.5731, lng: 126.9866
  },
  {
    id: 'MBX-015', shortCode: 'MBX-015', name: '홍대지점', type: LocationType.PARTNER,
    description: '연락처: 02-336-7972', address: '서울특별시 마포구 와우산로29길 72',
    name_en: 'Hongdae Branch', address_en: '72 Wausan-ro 29-gil, Mapo-gu, Seoul',
    name_ja: '弘大店', address_ja: 'ソウル特別市麻浦区臥牛山路29キル72',
    name_zh: '弘大店', address_zh: '首尔特别市麻浦区卧牛山路29街72',
        name_zh_tw: '弘大店',
    name_zh_hk: '弘大店',
    address_zh_tw: '首爾特別市麻浦區臥牛山路29街72',
    address_zh_hk: '首爾特別市麻浦區臥牛山路29街72',
    pickupGuide_en: 'Branch counter, please visit inside and mention Beeliber.',
    pickupGuide_ja: 'カウンターにお越しいただき、Beeliberの予約をお伝えください。',
    pickupGuide_zh: '请前往柜台告知您的Beeliber预订。',
    pickupGuide_zh_tw: '請前往櫃台告知您的Beeliber預訂。',
    pickupGuide_zh_hk: '請前往櫃台告知您的Beeliber預訂。',
    businessHours_en: '09:00 - 21:00',
    businessHours_ja: '09:00 - 21:00',
    businessHours_zh: '09:00 - 21:00',
businessHours: '09:00 - 21:00',
    supportsDelivery: true, supportsStorage: true,
    isOrigin: true, isDestination: true,
    isPartner: true, isActive: false, lat: 37.5563746, lng: 126.9265116
  },
  {
    id: 'MBX-016', shortCode: 'MBX-016', name: '명동점', type: LocationType.PARTNER,
    description: '연락처: 02-3789-0888', address: '서울특별시 중구 남대문로 52-1',
    name_en: 'Myeongdong Branch', address_en: '52-1 Namdaemun-ro, Jung-gu, Seoul',
    name_ja: '明洞店', address_ja: 'ソウル特別市中区南大門路52-1',
    name_zh: '明洞店', address_zh: '首尔特别市中区南大门路52-1',
        name_zh_tw: '明洞店',
    name_zh_hk: '明洞店',
    address_zh_tw: '首爾特別市中區南大門路52-1',
    address_zh_hk: '首爾特別市中區南大門路52-1',
    pickupGuide_en: 'Branch counter, please visit inside and mention Beeliber.',
    pickupGuide_ja: 'カウンターにお越しいただき、Beeliberの予約をお伝えください。',
    pickupGuide_zh: '请前往柜台告知您的Beeliber预订。',
    pickupGuide_zh_tw: '請前往櫃台告知您的Beeliber預訂。',
    pickupGuide_zh_hk: '請前往櫃台告知您的Beeliber預訂。',
    businessHours_en: '09:00 - 21:00',
    businessHours_ja: '09:00 - 21:00',
    businessHours_zh: '09:00 - 21:00',
businessHours: '09:00 - 21:00',
    supportsDelivery: true, supportsStorage: true,
    isOrigin: true, isDestination: true,
    isPartner: true, isActive: false, lat: 37.5615, lng: 126.9815
  },
  {
    id: 'MBX-017', shortCode: 'MBX-017', name: '평택지점', type: LocationType.PARTNER,
    description: '연락처: 031-651-8882', address: '경기도 평택시 팽성읍 안정순환로 110',
    name_en: 'Pyeongtaek Branch', address_en: '110 Anjeongsunhwan-ro, Paengseong-eup, Pyeongtaek-si, Gyeonggi-do',
    name_ja: '平澤店', address_ja: '京畿道平澤市彭城邑安仲循環路110',
    name_zh: '平泽店', address_zh: '京畿道平泽市彭城邑安仲循环路110',
        name_zh_tw: '平澤店',
    name_zh_hk: '平澤店',
    address_zh_tw: '京畿道平澤市彭城邑安仲循環路110',
    address_zh_hk: '京畿道平澤市彭城邑安仲循環路110',
    pickupGuide_en: 'Branch counter, please visit inside and mention Beeliber.',
    pickupGuide_ja: 'カウンターにお越しいただき、Beeliberの予約をお伝えください。',
    pickupGuide_zh: '请前往柜台告知您的Beeliber预订。',
    pickupGuide_zh_tw: '請前往櫃台告知您的Beeliber預訂。',
    pickupGuide_zh_hk: '請前往櫃台告知您的Beeliber預訂。',
    businessHours_en: '09:00 - 21:00',
    businessHours_ja: '09:00 - 21:00',
    businessHours_zh: '09:00 - 21:00',
businessHours: '09:00 - 21:00',
    supportsDelivery: true, supportsStorage: true,
    isOrigin: true, isDestination: true,
    isPartner: true, isActive: false, lat: 36.9921, lng: 127.1127
  },
  {
    id: 'MBX-018', shortCode: 'MBX-018', name: '송도지점', type: LocationType.PARTNER,
    description: '연락처: 032-858-8838', address: '인천광역시 연수구 인천타워대로132번길 30',
    name_en: 'Songdo Branch', address_en: '30 Incheontawae-daero 132beon-gil, Yeonsu-gu, Incheon',
    name_ja: '松島店', address_ja: '仁川広域市延寿区仁川タワー大路132番キル30',
    name_zh: '松岛店', address_zh: '仁川广域市延寿区仁川塔大路132号街30',
        name_zh_tw: '松島店',
    name_zh_hk: '松島店',
    address_zh_tw: '仁川廣域市延壽區仁川塔大路132號街30',
    address_zh_hk: '仁川廣域市延壽區仁川塔大路132號街30',
    pickupGuide_en: 'Branch counter, please visit inside and mention Beeliber.',
    pickupGuide_ja: 'カウンターにお越しいただき、Beeliberの予約をお伝えください。',
    pickupGuide_zh: '请前往柜台告知您的Beeliber预订。',
    pickupGuide_zh_tw: '請前往櫃台告知您的Beeliber預訂。',
    pickupGuide_zh_hk: '請前往櫃台告知您的Beeliber預訂。',
    businessHours_en: '09:00 - 21:00',
    businessHours_ja: '09:00 - 21:00',
    businessHours_zh: '09:00 - 21:00',
businessHours: '09:00 - 21:00',
    supportsDelivery: true, supportsStorage: true,
    isOrigin: true, isDestination: true,
    isPartner: true, isActive: false, lat: 37.385, lng: 126.643
  },
  {
    id: 'MBX-019', shortCode: 'MBX-019', name: '수원지점', type: LocationType.PARTNER,
    description: '연락처: 031-248-7888', address: '경기도 수원시 팔달구 향교로1번길 2',
    name_en: 'Suwon Branch', address_en: '2 Hyanggyo-ro 1beon-gil, Paldal-gu, Suwon-si, Gyeonggi-do',
    name_ja: '水原店', address_ja: '京畿道水原市八達区郷校路1번キル2',
    name_zh: '水原店', address_zh: '京畿道水原市八达区乡校路1号街2',
        name_zh_tw: '水原店',
    name_zh_hk: '水原店',
    address_zh_tw: '京畿道水原市八達區鄉校路1號街2',
    address_zh_hk: '京畿道水原市八達區鄉校路1號街2',
    pickupGuide_en: 'Branch counter, please visit inside and mention Beeliber.',
    pickupGuide_ja: 'カウンターにお越しいただき、Beeliberの予約をお伝えください。',
    pickupGuide_zh: '请前往柜台告知您的Beeliber预订。',
    pickupGuide_zh_tw: '請前往櫃台告知您的Beeliber預訂。',
    pickupGuide_zh_hk: '請前往櫃台告知您的Beeliber預訂。',
    businessHours_en: '09:00 - 21:00',
    businessHours_ja: '09:00 - 21:00',
    businessHours_zh: '09:00 - 21:00',
businessHours: '09:00 - 21:00',
    supportsDelivery: true, supportsStorage: true,
    isOrigin: true, isDestination: true,
    isPartner: true, isActive: false, lat: 37.2636, lng: 127.0286
  },
  {
    id: 'MBX-020', shortCode: 'MBX-020', name: '운서역지점', type: LocationType.PARTNER,
    description: '연락처: 032-746-1888', address: '인천 중구 운서동 2803-1 메가스타영종 제1동제1층 126호',
    name_en: 'Unseo Station Branch', address_en: '#126 Megastar Yeongjong, 2803-1 Unseo-dong, Jung-gu, Incheon',
    name_ja: '雲西駅店', address_ja: '仁川広域市中区雲西洞2803-1',
    name_zh: '云西站店', address_zh: '仁川广域市中区云西洞2803-1',
        name_zh_tw: '雲西站店',
    name_zh_hk: '雲西站店',
    address_zh_tw: '仁川廣域市中區雲西洞2803-1',
    address_zh_hk: '仁川廣域市中區雲西洞2803-1',
    pickupGuide_en: 'Branch counter, please visit inside and mention Beeliber.',
    pickupGuide_ja: 'カウンターにお越しいただき、Beeliberの予約をお伝えください。',
    pickupGuide_zh: '请前往柜台告知您的Beeliber预订。',
    pickupGuide_zh_tw: '請前往櫃台告知您的Beeliber預訂。',
    pickupGuide_zh_hk: '請前往櫃台告知您的Beeliber預訂。',
    businessHours_en: '09:00 - 21:00',
    businessHours_ja: '09:00 - 21:00',
    businessHours_zh: '09:00 - 21:00',
businessHours: '09:00 - 21:00',
    supportsDelivery: true, supportsStorage: true,
    isOrigin: true, isDestination: true,
    isPartner: true, isActive: false, lat: 37.4925, lng: 126.4914
  },
  {
    id: 'MBX-021', shortCode: 'MBX-021', name: '부평지점', type: LocationType.PARTNER,
    description: '연락처: 032-362-8881', address: '인천광역시 부평구 부평동 546-64',
    name_en: 'Bupyeong Branch', address_en: '546-64 Bupyeong-dong, Bupyeong-gu, Incheon',
    name_ja: '富平店', address_ja: '仁川広域市富平区富平洞546-64',
    name_zh: '富平店', address_zh: '仁川广域市富平区富平洞546-64',
        name_zh_tw: '富平店',
    name_zh_hk: '富平店',
    address_zh_tw: '仁川廣域市富平區富平洞546-64',
    address_zh_hk: '仁川廣域市富平區富平洞546-64',
    pickupGuide_en: 'Branch counter, please visit inside and mention Beeliber.',
    pickupGuide_ja: 'カウンターにお越しいただき、Beeliberの予約をお伝えください。',
    pickupGuide_zh: '请前往柜台告知您的Beeliber预订。',
    pickupGuide_zh_tw: '請前往櫃台告知您的Beeliber預訂。',
    pickupGuide_zh_hk: '請前往櫃台告知您的Beeliber預訂。',
    businessHours_en: '09:00 - 21:00',
    businessHours_ja: '09:00 - 21:00',
    businessHours_zh: '09:00 - 21:00',
businessHours: '09:00 - 21:00',
    supportsDelivery: true, supportsStorage: true,
    isOrigin: true, isDestination: true,
    isPartner: true, isActive: false, lat: 37.4894, lng: 126.7248
  },
  {
    id: 'MBX-022', shortCode: 'MBX-022', name: '김포지점', type: LocationType.PARTNER,
    description: '연락처: 031-989-4448', address: '경기도 김포시 대곶면 율마로 37',
    name_en: 'Gimpo Branch', address_en: '37 Yulma-ro, Daegot-myeon, Gimpo-si, Gyeonggi-do',
    name_ja: '金浦店', address_ja: '京畿道金浦市大串面栗馬路37',
    name_zh: '金浦店', address_zh: '京畿道金浦市大串面栗马路37',
        name_zh_tw: '金浦店',
    name_zh_hk: '金浦店',
    address_zh_tw: '京畿道金浦市大串面栗馬路37',
    address_zh_hk: '京畿道金浦市大串面栗馬路37',
    pickupGuide_en: 'Branch counter, please visit inside and mention Beeliber.',
    pickupGuide_ja: 'カウンターにお越しいただき、Beeliberの予約をお伝えください。',
    pickupGuide_zh: '请前往柜台告知您的Beeliber预订。',
    pickupGuide_zh_tw: '請前往櫃台告知您的Beeliber預訂。',
    pickupGuide_zh_hk: '請前往櫃台告知您的Beeliber預訂。',
    businessHours_en: '09:00 - 21:00',
    businessHours_ja: '09:00 - 21:00',
    businessHours_zh: '09:00 - 21:00',
businessHours: '09:00 - 21:00',
    supportsDelivery: true, supportsStorage: true,
    isOrigin: true, isDestination: true,
    isPartner: true, isActive: false, lat: 37.6151, lng: 126.7153
  },
  {
    id: 'MBX-023', shortCode: 'MBX-023', name: '창원지점', type: LocationType.PARTNER,
    description: '연락처: 055-267-8881', address: '경상남도 창원시 성산구 상남로 118',
    name_en: 'Changwon Branch', address_en: '118 Sangnam-ro, Seongsan-gu, Changwon-si, Gyeongsangnam-do',
    name_ja: '昌原店', address_ja: '慶尚南道昌原市城山区上南路118',
    name_zh: '昌原店', address_zh: '庆尚南道昌原市城山区上南路118',
        name_zh_tw: '昌原店',
    name_zh_hk: '昌原店',
    address_zh_tw: '慶尚南道昌原市城山區上南路118',
    address_zh_hk: '慶尚南道昌原市城山區上南路118',
    pickupGuide_en: 'Branch counter, please visit inside and mention Beeliber.',
    pickupGuide_ja: 'カウンターにお越しいただき、Beeliberの予約をお伝えください。',
    pickupGuide_zh: '请前往柜台告知您的Beeliber预订。',
    pickupGuide_zh_tw: '請前往櫃台告知您的Beeliber預訂。',
    pickupGuide_zh_hk: '請前往櫃台告知您的Beeliber預訂。',
    businessHours_en: '09:00 - 21:00',
    businessHours_ja: '09:00 - 21:00',
    businessHours_zh: '09:00 - 21:00',
businessHours: '09:00 - 21:00',
    supportsDelivery: true, supportsStorage: true,
    isOrigin: true, isDestination: true,
    isPartner: true, isActive: false, lat: 35.2281, lng: 128.6811
  },
  {
    id: 'MBX-024', shortCode: 'MBX-024', name: '울산삼산지점', type: LocationType.PARTNER,
    description: '연락처: 052-258-8881', address: '울산시 남구 삼산동 1479-5번지 1층 104호',
    name_en: 'Ulsan Samsan Branch', address_en: '#104, 1479-5 Samsan-dong, Nam-gu, Ulsan',
    name_ja: '蔚山三山店', address_ja: '蔚山広域市南区三山洞1479-5',
    name_zh: '蔚山三山店', address_zh: '蔚山广域市南区三山洞1479-5',
        name_zh_tw: '蔚山三山店',
    name_zh_hk: '蔚山三山店',
    address_zh_tw: '蔚山廣域市南區三山洞1479-5',
    address_zh_hk: '蔚山廣域市南區三山洞1479-5',
    pickupGuide_en: 'Branch counter, please visit inside and mention Beeliber.',
    pickupGuide_ja: 'カウンターにお越しいただき、Beeliberの予約をお伝えください。',
    pickupGuide_zh: '请前往柜台告知您的Beeliber预订。',
    pickupGuide_zh_tw: '請前往櫃台告知您的Beeliber預訂。',
    pickupGuide_zh_hk: '請前往櫃台告知您的Beeliber預訂。',
    businessHours_en: '09:00 - 21:00',
    businessHours_ja: '09:00 - 21:00',
    businessHours_zh: '09:00 - 21:00',
businessHours: '09:00 - 21:00',
    supportsDelivery: true, supportsStorage: true,
    isOrigin: true, isDestination: true,
    isPartner: true, isActive: false, lat: 35.5392, lng: 129.3114
  },
  {
    id: 'MBX-025', shortCode: 'MBX-025', name: '광안리지점', type: LocationType.PARTNER,
    description: '연락처: 051-758-8858', address: '부산시 수영구 광안로 20',
    name_en: 'Gwangalli Branch', address_en: '20 Gwangan-ro, Suyeong-gu, Busan',
    name_ja: '広安里店', address_ja: '釜山広域市水営区広安路20',
    name_zh: '广安里店', address_zh: '釜山广域市水营区广安路20',
        name_zh_tw: '廣安里店',
    name_zh_hk: '廣安里店',
    address_zh_tw: '釜山廣域市水營區廣安路20',
    address_zh_hk: '釜山廣域市水營區廣安路20',
    pickupGuide_en: 'Branch counter, please visit inside and mention Beeliber.',
    pickupGuide_ja: 'カウンターにお越しいただき、Beeliberの予約をお伝えください。',
    pickupGuide_zh: '请前往柜台告知您的Beeliber预订。',
    pickupGuide_zh_tw: '請前往櫃台告知您的Beeliber預訂。',
    pickupGuide_zh_hk: '請前往櫃台告知您的Beeliber預訂。',
    businessHours_en: '09:00 - 21:00',
    businessHours_ja: '09:00 - 21:00',
    businessHours_zh: '09:00 - 21:00',
businessHours: '09:00 - 21:00',
    supportsDelivery: true, supportsStorage: true,
    isOrigin: true, isDestination: true,
    isPartner: true, isActive: false, lat: 35.1531, lng: 129.1189
  },
  {
    id: 'MBX-026', shortCode: 'MBX-026', name: '부산역지점', type: LocationType.PARTNER,
    description: '연락처: 051-467-8880', address: '부산광역시 동구 중앙대로203번길 10',
    name_en: 'Busan Station Branch', address_en: '10 Jungang-daero 203beon-gil, Dong-gu, Busan',
    name_ja: '釜山駅店', address_ja: '釜山広域市東区中央大路203番キル10',
    name_zh: '釜山站店', address_zh: '釜山广域市东区中央大路203号街10',
        name_zh_tw: '釜山站店',
    name_zh_hk: '釜山站店',
    address_zh_tw: '釜山廣域市東區中央大路203號街10',
    address_zh_hk: '釜山廣域市東區中央大路203號街10',
    pickupGuide_en: 'Branch counter, please visit inside and mention Beeliber.',
    pickupGuide_ja: 'カウンターにお越しいただき、Beeliberの予約をお伝えください。',
    pickupGuide_zh: '请前往柜台告知您的Beeliber预订。',
    pickupGuide_zh_tw: '請前往櫃台告知您的Beeliber預訂。',
    pickupGuide_zh_hk: '請前往櫃台告知您的Beeliber預訂。',
    businessHours_en: '09:00 - 21:00',
    businessHours_ja: '09:00 - 21:00',
    businessHours_zh: '09:00 - 21:00',
businessHours: '09:00 - 21:00',
    supportsDelivery: true, supportsStorage: true,
    isOrigin: true, isDestination: true,
    isPartner: true, isActive: false, lat: 35.1147, lng: 129.0401
  },
  {
    id: 'MBX-027', shortCode: 'MBX-027', name: '대구지점', type: LocationType.PARTNER,
    description: '연락처: 053-423-0888', address: '대구광역시 중구 덕산동 124-40 101호',
    name_en: 'Daegu Branch', address_en: '#101, 124-40 Deoksan-dong, Jung-gu, Daegu',
    name_ja: '大邱店', address_ja: '大邱広域市中区徳山洞124-40',
    name_zh: '大邱店', address_zh: '大邱广域市中区德山洞124-40',
        name_zh_tw: '大邱店',
    name_zh_hk: '大邱店',
    address_zh_tw: '大邱廣域市中區德山洞124-40',
    address_zh_hk: '大邱廣域市中區德山洞124-40',
    pickupGuide_en: 'Branch counter, please visit inside and mention Beeliber.',
    pickupGuide_ja: 'カウンターにお越しいただき、Beeliberの予約をお伝えください。',
    pickupGuide_zh: '请前往柜台告知您的Beeliber预订。',
    pickupGuide_zh_tw: '請前往櫃台告知您的Beeliber預訂。',
    pickupGuide_zh_hk: '請前往櫃台告知您的Beeliber預訂。',
    businessHours_en: '09:00 - 21:00',
    businessHours_ja: '09:00 - 21:00',
    businessHours_zh: '09:00 - 21:00',
businessHours: '09:00 - 21:00',
    supportsDelivery: true, supportsStorage: true,
    isOrigin: true, isDestination: true,
    isPartner: true, isActive: false, lat: 35.8655, lng: 128.5934
  },
  {
    id: 'MBX-028', shortCode: 'MBX-028', name: '김해공항지점', type: LocationType.PARTNER,
    description: '연락처: 051-973-9996', address: '부산광역시 강서구 공항진입로 165',
    name_en: 'Gimhae Airport Branch', address_en: '165 Gonghangjinip-ro, Gangseo-gu, Busan',
    name_ja: '金海空港店', address_ja: '釜山広域市江西区空港進入路165',
    name_zh: '金海机场店', address_zh: '釜山广域市江西区机场进入路165',
        name_zh_tw: '金海機場店',
    name_zh_hk: '金海機場店',
    address_zh_tw: '釜山廣域市江西區機場進入路165',
    address_zh_hk: '釜山廣域市江西區機場進入路165',
    pickupGuide_en: 'Branch counter, please visit inside and mention Beeliber.',
    pickupGuide_ja: 'カウンターにお越しいただき、Beeliberの予約をお伝えください。',
    pickupGuide_zh: '请前往柜台告知您的Beeliber预订。',
    pickupGuide_zh_tw: '請前往櫃台告知您的Beeliber預訂。',
    pickupGuide_zh_hk: '請前往櫃台告知您的Beeliber預訂。',
    businessHours_en: '09:00 - 21:00',
    businessHours_ja: '09:00 - 21:00',
    businessHours_zh: '09:00 - 21:00',
businessHours: '09:00 - 21:00',
    supportsDelivery: true, supportsStorage: true,
    isOrigin: true, isDestination: true,
    isPartner: true, isActive: false, lat: 35.1718, lng: 128.9483
  },
  {
    id: 'MBX-029', shortCode: 'MBX-029', name: '남포지점', type: LocationType.PARTNER,
    description: '연락처: 051-245-9998', address: '부산광역시 중구 광복로 38',
    name_en: 'Nampo Branch', address_en: '38 Gwangbok-ro, Jung-gu, Busan',
    name_ja: '南浦店', address_ja: '釜山広域市中区光復路38',
    name_zh: '南浦店', address_zh: '釜山广域市中区光复路38',
        name_zh_tw: '南浦店',
    name_zh_hk: '南浦店',
    address_zh_tw: '釜山廣域市中區光復路38',
    address_zh_hk: '釜山廣域市中區光復路38',
    pickupGuide_en: 'Branch counter, please visit inside and mention Beeliber.',
    pickupGuide_ja: 'カウンターにお越しいただき、Beeliberの予約をお伝えください。',
    pickupGuide_zh: '请前往柜台告知您的Beeliber预订。',
    pickupGuide_zh_tw: '請前往櫃台告知您的Beeliber預訂。',
    pickupGuide_zh_hk: '請前往櫃台告知您的Beeliber預訂。',
    businessHours_en: '09:00 - 21:00',
    businessHours_ja: '09:00 - 21:00',
    businessHours_zh: '09:00 - 21:00',
businessHours: '09:00 - 21:00',
    supportsDelivery: true, supportsStorage: true,
    isOrigin: true, isDestination: true,
    isPartner: true, isActive: false, lat: 35.0985, lng: 129.0284
  },
  {
    id: 'MBX-030', shortCode: 'MBX-030', name: '해운대지점', type: LocationType.PARTNER,
    description: '연락처: 051-742-9998', address: '부산광역시 해운대구 중동 1392-100 씨클라우드호텔 1층',
    name_en: 'Haeundae Branch', address_en: '1F Seacloud Hotel, 1392-100 Jung-dong, Haeundae-gu, Busan',
    name_ja: '海雲台店', address_ja: '釜山広域市海雲台区中洞1392-100',
    name_zh: '海云台店', address_zh: '釜山广域市海云台区中洞1392-100',
        name_zh_tw: '海雲台店',
    name_zh_hk: '海雲台店',
    address_zh_tw: '釜山廣域市海雲台區中洞1392-100',
    address_zh_hk: '釜山廣域市海雲台區中洞1392-100',
    pickupGuide_en: 'Branch counter, please visit inside and mention Beeliber.',
    pickupGuide_ja: 'カウンターにお越しいただき、Beeliberの予約をお伝えください。',
    pickupGuide_zh: '请前往柜台告知您的Beeliber预订。',
    pickupGuide_zh_tw: '請前往櫃台告知您的Beeliber預訂。',
    pickupGuide_zh_hk: '請前往櫃台告知您的Beeliber預訂。',
    businessHours_en: '09:00 - 21:00',
    businessHours_ja: '09:00 - 21:00',
    businessHours_zh: '09:00 - 21:00',
businessHours: '09:00 - 21:00',
    supportsDelivery: true, supportsStorage: true,
    isOrigin: true, isDestination: true,
    isPartner: true, isActive: false, lat: 35.1595, lng: 129.1627
  },
  {
    id: 'MBX-031', shortCode: 'MBX-031', name: '제주동문시장점', type: LocationType.PARTNER,
    description: '연락처: 064-755-8881', address: '제주특별자치도 제주시 관덕로64',
    name_en: 'Jeju Dongmun Market Branch', address_en: '64 Gwandeok-ro, Jeju-si, Jeju-do',
    name_ja: '済州東門市場店', address_ja: '済州特別自治道済州市観徳路64',
    name_zh: '济州东门市场店', address_zh: '济州特别自治道济州市观德路64',
        name_zh_tw: '濟州東門市場店',
    name_zh_hk: '濟州東門市場店',
    address_zh_tw: '濟州特別自治道濟州市觀德路64',
    address_zh_hk: '濟州特別自治道濟州市觀德路64',
    pickupGuide_en: 'Branch counter, please visit inside and mention Beeliber.',
    pickupGuide_ja: 'カウンターにお越しいただき、Beeliberの予約をお伝えください。',
    pickupGuide_zh: '请前往柜台告知您的Beeliber预订。',
    pickupGuide_zh_tw: '請前往櫃台告知您的Beeliber預訂。',
    pickupGuide_zh_hk: '請前往櫃台告知您的Beeliber預訂。',
    businessHours_en: '09:00 - 21:00',
    businessHours_ja: '09:00 - 21:00',
    businessHours_zh: '09:00 - 21:00',
businessHours: '09:00 - 21:00',
    supportsDelivery: true, supportsStorage: true,
    isOrigin: true, isDestination: true,
    isPartner: true, isActive: false, lat: 33.4996, lng: 126.5312
  },
  {
    id: 'MBX-032', shortCode: 'MBX-032', name: '제주지점', type: LocationType.PARTNER,
    description: '연락처: 064-743-8887', address: '제주특별자치도 제주시 원노형4길 1',
    name_en: 'Jeju Branch', address_en: '1 Wonnohyeong 4-gil, Jeju-si, Jeju-do',
    name_ja: '済州店', address_ja: '済州特別自治道済州市元老衡4キル1',
    name_zh: '济州店', address_zh: '济州特别自治道济州市元老衡4街1',
        name_zh_tw: '濟州店',
    name_zh_hk: '濟州店',
    address_zh_tw: '濟州特別自治道濟州市元老衡4街1',
    address_zh_hk: '濟州特別自治道濟州市元老衡4街1',
    pickupGuide_en: 'Branch counter, please visit inside and mention Beeliber.',
    pickupGuide_ja: 'カウンターにお越しいただき、Beeliberの予約をお伝えください。',
    pickupGuide_zh: '请前往柜台告知您的Beeliber预订。',
    pickupGuide_zh_tw: '請前往櫃台告知您的Beeliber預訂。',
    pickupGuide_zh_hk: '請前往櫃台告知您的Beeliber預訂。',
    businessHours_en: '09:00 - 21:00',
    businessHours_ja: '09:00 - 21:00',
    businessHours_zh: '09:00 - 21:00',
businessHours: '09:00 - 21:00',
    supportsDelivery: true, supportsStorage: true,
    isOrigin: true, isDestination: true,
    isPartner: true, isActive: false, lat: 33.4996, lng: 126.5312
  },
  {
    id: 'MBX-033', shortCode: 'MBX-033', name: '광주지점', type: LocationType.PARTNER,
    description: '연락처: 062-226-7972', address: '광주광역시 서구 내방로 367',
    name_en: 'Gwangju Branch', address_en: '367 Naebang-ro, Seo-gu, Gwangju',
    name_ja: '光州店', address_ja: '光州広域市西区内防路367',
    name_zh: '光州店', address_zh: '光州广域市西区内防路367',
        name_zh_tw: '光州店',
    name_zh_hk: '光州店',
    address_zh_tw: '光州廣域市西區內防路367',
    address_zh_hk: '光州廣域市西區內防路367',
    pickupGuide_en: 'Branch counter, please visit inside and mention Beeliber.',
    pickupGuide_ja: 'カウンターにお越しいただき、Beeliberの予約をお伝えください。',
    pickupGuide_zh: '请前往柜台告知您的Beeliber预订。',
    pickupGuide_zh_tw: '請前往櫃台告知您的Beeliber預訂。',
    pickupGuide_zh_hk: '請前往櫃台告知您的Beeliber預訂。',
    businessHours_en: '09:00 - 21:00',
    businessHours_ja: '09:00 - 21:00',
    businessHours_zh: '09:00 - 21:00',
businessHours: '09:00 - 21:00',
    supportsDelivery: true, supportsStorage: true,
    isOrigin: true, isDestination: true,
    isPartner: true, isActive: false, lat: 35.1595, lng: 126.8526
  }
];

export const NAV_LINKS = [
  { name: '서비스 소개', href: '#services' },
  { name: '지점 안내', href: '#locations' },
  { name: '배송 조회', href: '#tracking' },
  { name: '제휴 문의', href: '#partners' },
];
